apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shinyproxy

bases:
  - ../../../bases/shinyproxy/
  - ../../../bases/redis/
  - ../../../bases/namespaced/operator

resources:
 - shinyproxy.yaml
